export interface StudentRequest {
  studentMatricNum?: string,
  studentName?: string,
  studentAddress?: string,
  studentEmail?: string,
  studentPhone?: string,
  studentPassword?: string,
  studentCampus?: string,
  studentCourse?: string,
  studentClass?: string,
  studentProject?: string,
  studentStatus?: string,
  studentCV?: string,
  studentCVFileName?: string,
  studentMiniTranscript?: string,
  studentMiniTranscriptFileName?: string,
  studentCoverLetter?: string,
  studentCoverLetterFileName?: string,
  studentCourseOutline?: string,
  studentCourseOutlineFileName?: string,
  studentSL?: string,
  studentSLFileName?: string,
  industrySvId?: string,
  academicSvId?: string,
  coordinatorId?: string
}